(()=>{
const E=window.DUPB_ENTRIES||[],M=window.DUPB_METADATA||window.DUPB_RELEASE_INFO||{},CFG=window.DUPB_CONFIG||{},C=window.DUPB_COMMON;
let pf='all',sf='all',alpha='all',pos='all',vtype='all',sem='all',flag='all',sel=null,renderRows=[],rendered=0;
const senses=e=>e.entries.flatMap(x=>x.senses);
const predCount=e=>senses(e).filter(x=>x.predicator).length;
const nonPredCount=e=>senses(e).length-predCount(e);
const profile=e=>{const p=predCount(e),n=nonPredCount(e);return p===0?'nonly':n===0?'allS':'mixed'};
const plural=(n,o,m)=>Number(n)===1?o:m;
const qel=()=>document.querySelector('#q');
const SEARCH_INDEX=E.map(e=>({e,lemma:C.fold(e.lemma),description:C.fold(senses(e).map(s=>(s.description||'')+' '+(s.source_text||'')).join(' '))}));
function okProfile(e){if(pf==='all')return true;if(pf==='hasS')return predCount(e)>0;return profile(e)===pf}
function senseEligible(s){if(sf==='S'&&!s.predicator)return false;if(sf==='N'&&s.predicator)return false;if(pos!=='all'&&s.pos!==pos)return false;if(vtype!=='all'&&s.verb_type!==vtype)return false;if(sem!=='all'&&s.semantic_class!==sem)return false;if(flag!=='all'&&!(s.flags||[]).includes(flag))return false;return true}
function visibleSenses(e){return senses(e).filter(senseEligible)}
function boundedNear(a,b){if(Math.abs(a.length-b.length)>2||a.slice(0,3)!==b.slice(0,3))return false;if(a===b)return true;const m=a.length,n=b.length,prev=Array.from({length:n+1},(_,i)=>i),cur=new Array(n+1);for(let i=1;i<=m;i++){cur[0]=i;let rowMin=cur[0];for(let j=1;j<=n;j++){cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));rowMin=Math.min(rowMin,cur[j])}if(rowMin>2)return false;for(let j=0;j<=n;j++)prev[j]=cur[j]}return prev[n]<=2}
function rank(x,q){if(!q)return 0;if(x.lemma===q)return 0;if(x.lemma.startsWith(q))return 10;if(x.lemma.includes(q))return 20;if(q.length>=4&&boundedNear(x.lemma,q))return 28;if(x.description.includes(q))return 40;return null}
function rows(){
 const q=C.fold(qel().value.trim()),min=Number(document.querySelector('#minSenses').value),max=Number(document.querySelector('#maxSenses').value),out=[];
 for(const x of SEARCH_INDEX){const e=x.e,n=senses(e).length;if(n<min||n>max||!okProfile(e))continue;if(alpha!=='all'&&!x.lemma.startsWith(C.fold(alpha)))continue;const r=rank(x,q);if(r===null||visibleSenses(e).length===0)continue;out.push({e,r,n:x.lemma})}
 out.sort((a,b)=>a.r-b.r||a.n.localeCompare(b.n,'pt-BR'));return out.map(x=>x.e)
}
function meta(e){const ss=visibleSenses(e),p=ss.filter(s=>s.predicator).length,n=ss.length-p;if(sf==='S')return `${C.format(p)} ${plural(p,'acepção predicadora','acepções predicadoras')}`;if(sf==='N')return `${C.format(n)} ${plural(n,'acepção não predicadora','acepções não predicadoras')}`;const a=[`${C.format(ss.length)} ${plural(ss.length,'acepção','acepções')}`];if(p)a.push(`${C.format(p)} ${plural(p,'predicadora','predicadoras')}`);if(n)a.push(`${C.format(n)} ${plural(n,'não predicadora','não predicadoras')}`);return a.join(' · ')}
function renderMore(batch=140){const h=document.querySelector('#list'),end=Math.min(rendered+batch,renderRows.length);if(end<=rendered)return;h.insertAdjacentHTML('beforeend',renderRows.slice(rendered,end).map(e=>`<button class="lem ${sel===e.lemma?'sel':''}" data-l="${C.esc(e.lemma)}"><span class="lex-main"><strong>${C.esc(e.lemma)}</strong><small>${C.esc(meta(e))}</small></span><span class="chev">›</span></button>`).join(''));h.querySelectorAll('.lem:not([data-bound])').forEach(b=>{b.dataset.bound='1';b.onclick=()=>show(b.dataset.l)});rendered=end}
function list(){const r=rows(),vis=r.reduce((a,e)=>a+visibleSenses(e).length,0);document.querySelector('#count').textContent=`${C.format(r.length)} ${plural(r.length,CFG.itemSingular,CFG.itemPlural)} · ${C.format(vis)} ${plural(vis,'acepção','acepções')}`;document.querySelector('#list').innerHTML='';renderRows=r;rendered=0;renderMore();updateCounts();activeFilters()}
function updateCounts(){const base=E.filter(e=>{const n=senses(e).length,min=Number(document.querySelector('#minSenses').value),max=Number(document.querySelector('#maxSenses').value);if(n<min||n>max)return false;const q=C.fold(qel().value.trim());const x={lemma:C.fold(e.lemma),description:C.fold(senses(e).map(s=>(s.description||'')+' '+(s.source_text||'')).join(' '))};if(rank(x,q)===null)return false;if(alpha!=='all'&&!x.lemma.startsWith(C.fold(alpha)))return false;return true});const pc={all:base.length,hasS:base.filter(e=>predCount(e)>0).length,allS:base.filter(e=>profile(e)==='allS').length,mixed:base.filter(e=>profile(e)==='mixed').length,nonly:base.filter(e=>profile(e)==='nonly').length};document.querySelectorAll('#profiles button').forEach(b=>b.querySelector('.facet-count').textContent=C.format(pc[b.dataset.p]||0))}
function activeFilters(){const h=document.querySelector('#activeFilters'),arr=[];const q=qel().value.trim();if(q)arr.push(['Busca: '+q,()=>{qel().value='';list()}]);if(pf!=='all')arr.push(['Perfil',()=>{pf='all';sync();list()}]);if(sf!=='all')arr.push([sf==='S'?'Predicadoras':'Não predicadoras',()=>{sf='all';sync();sel?renderEntry(current()):list()}]);if(pos!=='all')arr.push([POS_LABELS[pos]||pos,()=>{pos='all';syncExtra();list()}]);if(vtype!=='all')arr.push([vtype,()=>{vtype='all';syncExtra();list()}]);if(sem!=='all')arr.push([sem,()=>{sem='all';syncExtra();list()}]);if(flag!=='all')arr.push([flag,()=>{flag='all';syncExtra();list()}]);if(alpha!=='all')arr.push(['Letra: '+alpha,()=>{alpha='all';alphabet();list()}]);h.innerHTML='';h.hidden=!arr.length;arr.forEach(([t,fn])=>{const b=document.createElement('button');b.className='filter-chip';b.textContent=t+' ×';b.onclick=fn;h.appendChild(b)})}
const POS_LABELS=CFG.posLabels||{};
function current(){return E.find(x=>x.lemma===sel)}
function updateUrl(l){const u=new URL(location.href);l?u.searchParams.set('lemma',l):u.searchParams.delete('lemma');history.pushState({},'',u)}
function summary(e){const all=senses(e),vis=visibleSenses(e);if(vis.length===all.length)return meta(e);return `${meta(e)} de ${C.format(all.length)} ${plural(all.length,'acepção no DUPB','acepções no DUPB')}`}
function card(s){const badges=[`<span class="badge ${s.predicator?'S':'N'}">${s.predicator?'Predicador':'Não predicador'}</span>`];if(CFG.kind==='nonnv')badges.push(`<span class="badge pos">${C.esc(s.pos_label)}</span>`);if(CFG.kind==='verb'){badges.push(`<span class="badge meta">${C.esc(s.verb_type)}</span>`);if(s.semantic_class&&s.semantic_class!=='Não especificada')badges.push(`<span class="badge meta">${C.esc(s.semantic_class)}</span>`)}const body=s.description?`<p class="desc">${C.esc(s.description)}</p>`:`<div class="source-fallback"><b>Texto da acepção no DUPB</b><p>${C.esc(s.source_text||'Texto não disponível.')}</p></div>`;const extra=CFG.kind==='verb'&&(s.flags||[]).length?`<p class="meta-line">${C.esc(s.flags.join(' · '))}</p>`:'';return `<article class="card"><div class="top"><span class="num">${C.esc(senseHeading(s))}</span><span class="badge-row">${badges.join('')}</span></div>${body}${extra}</article>`}
function renderEntry(e){sel=e.lemma;document.querySelector('#intro').hidden=true;document.querySelector('#entry').hidden=false;document.querySelector('#title').textContent=e.lemma;document.querySelector('#summary').textContent=summary(e);const vis=visibleSenses(e);const groups=e.entries.map(g=>{const ss=g.senses.filter(senseEligible);if(!ss.length)return '';const title=e.entries.length>1?`<h3>${C.esc(e.lemma)}<sup>${g.entry}</sup></h3>`:'';return `<section class="grp">${title}${ss.map(card).join('')}</section>`}).join('')||'<p>Nenhuma acepção corresponde ao filtro atual.</p>';document.querySelector('#groups').innerHTML=groups;const all=senses(e),p=all.filter(s=>s.predicator).length;let dl=`<dt>Acepções</dt><dd>${C.format(all.length)}</dd><dt>Predicadoras</dt><dd>${C.format(p)}</dd><dt>Não predicadoras</dt><dd>${C.format(all.length-p)}</dd>`;if(e.entries.length>1)dl+=`<dt>Entradas lexicográficas</dt><dd>${e.entries.length}</dd>`;if(CFG.kind==='nonnv')dl+=`<dt>Classes</dt><dd>${Object.keys(e.pos_counts).map(x=>C.esc(x)).join(', ')}</dd>`;document.querySelector('#lexicalData').innerHTML=dl;list()}
function show(l,write=true){const e=E.find(x=>x.lemma===l);if(!e)return;if(write)updateUrl(l);renderEntry(e)}
function alphabet(){const chars=['all',...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'];document.querySelector('#alphabet').innerHTML=chars.map(x=>`<button data-a="${x}" class="alpha ${x===alpha?'on':''}">${x==='all'?'Todos':x}</button>`).join('');document.querySelectorAll('.alpha').forEach(b=>b.onclick=()=>{alpha=b.dataset.a;alphabet();list()})}
function sync(){document.querySelectorAll('#profiles button').forEach(b=>{const on=b.dataset.p===pf;b.classList.toggle('on',on);b.setAttribute('aria-pressed',on)});document.querySelectorAll('#senseFilters button').forEach(b=>{const on=b.dataset.s===sf;b.classList.toggle('on',on);b.setAttribute('aria-pressed',on)})}
function syncExtra(){[['#posFilter',pos],['#verbType',vtype],['#semClass',sem],['#flagFilter',flag]].forEach(([id,val])=>{const el=document.querySelector(id);if(el)el.value=val})}
let frame=null;qel().oninput=()=>{if(frame)cancelAnimationFrame(frame);frame=requestAnimationFrame(list)};
document.querySelectorAll('#profiles button').forEach(b=>b.onclick=()=>{pf=b.dataset.p;sync();list()});document.querySelectorAll('#senseFilters button').forEach(b=>b.onclick=()=>{sf=b.dataset.s;sync();sel?renderEntry(current()):list()});document.querySelector('#minSenses').onchange=list;document.querySelector('#maxSenses').onchange=list;
for(const [id,setter] of [['#posFilter',v=>pos=v],['#verbType',v=>vtype=v],['#semClass',v=>sem=v],['#flagFilter',v=>flag=v]]){const el=document.querySelector(id);if(el)el.onchange=()=>{setter(el.value);sel?renderEntry(current()):list()}}
function exportFilePart(v){return String(v||'').normalize('NFC').trim().replace(/[\u0000-\u001f<>:"/\\|?*]+/g,'-').replace(/\s+/g,'-').replace(/-+/g,'-').replace(/^[ .-]+|[ .-]+$/g,'')||'entrada'}
function senseHeading(x){if(x.sense!==null&&x.sense!==undefined)return `Sentido DUPB ${x.sense}`;if(x.sense_label==='IMPLICIT')return 'Acepção implícita no DUPB';return 'Acepção sem número no DUPB'}
document.querySelector('#jsonOne').onclick=()=>{const e=current();if(!e)return;const b=new Blob([JSON.stringify(e,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${exportFilePart(e.lemma)}-verbal-explorer.json`;a.click();URL.revokeObjectURL(a.href)};
document.querySelector('#jsonlOne').onclick=()=>{const e=current();if(!e)return;const rows=e.entries.flatMap(g=>g.senses.map(s=>JSON.stringify({lemma:e.lemma,entry:g.entry,...s}))).join('\n')+'\n',b=new Blob([rows],{type:'application/x-ndjson'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${exportFilePart(e.lemma)}-verbal-explorer.jsonl`;a.click();URL.revokeObjectURL(a.href)};
document.querySelector('#copyLink').onclick=e=>sel&&C.copy(C.entryUrl(sel),e.currentTarget);document.querySelector('#copyCitation').onclick=e=>sel&&C.copy(C.citation(sel),e.currentTarget);document.querySelector('#copyBibtex').onclick=e=>sel&&C.copy(C.bibtex(sel),e.currentTarget);
const statSpec=CFG.kind==='verb'?[['total_lemmas','verbos'],['has_predicator_lemmas','com alguma acepção predicadora'],['functional_senses','acepções funcionais'],['senses','acepções'],['predicator_senses','acepções predicadoras'],['non_predicator_senses','acepções não predicadoras']]:[['total_lemmas','entradas de consulta'],['pos_count','classes'],['has_predicator_lemmas','com alguma acepção predicadora'],['senses','acepções'],['predicator_senses','acepções predicadoras'],['non_predicator_senses','acepções não predicadoras']];
document.querySelector('#stats').innerHTML=statSpec.map(([k,t])=>`<div class="stat"><b>${C.format(M[k])}</b><span>${t}</span></div>`).join('');
alphabet();sync();syncExtra();list();const requested=new URL(location.href).searchParams.get('lemma');if(requested){const ex=E.find(e=>C.fold(e.lemma)===C.fold(requested));if(ex){qel().value=ex.lemma;renderEntry(ex)}}window.addEventListener('scroll',()=>{if(window.innerHeight+window.scrollY>=document.body.offsetHeight-700)renderMore()});
})();